# Generated by Django 5.0.4 on 2024-05-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_year_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name_plural': 'Years'},
        ),
    ]
